# Generated by Django 6.0.1 on 2026-03-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_customorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=255)),
                ('email_host', models.CharField(default='smtp.example.com', max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_use_ssl', models.BooleanField(default=False)),
                ('email_host_user', models.CharField(blank=True, max_length=255)),
                ('email_host_password', models.CharField(blank=True, max_length=255)),
                ('default_from_email', models.EmailField(default='noreply@example.com', max_length=254)),
                ('notify_email', models.EmailField(blank=True, help_text='Email for administrative notifications', max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
