# Generated by Django 6.0.1 on 2026-03-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_emailconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='default_from_email',
            field=models.CharField(default='noreply@example.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='notify_email',
            field=models.CharField(blank=True, help_text='Email for administrative notifications', max_length=255, null=True),
        ),
    ]
