# Generated by Django 6.0.1 on 2026-02-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentgateway',
            options={'ordering': ['-created_at']},
        ),
    ]
