# Generated by Django 6.0.1 on 2026-03-01 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_paymentgateway_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentgateway',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
