# Generated by Django 6.0.1 on 2026-02-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_featured',
        ),
    ]
