# Generated by Django 6.0.1 on 2026-03-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_set',
            field=models.BooleanField(default=False),
        ),
    ]
