# Generated by Django 6.0.1 on 2026-04-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_filtergroup_remove_category_parent_and_more'),
        ('reviews', '0007_remove_shopbycatalogsection_categories_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterUniqueTogether(
            name='filteroption',
            unique_together={('group', 'slug')},
        ),
    ]
