# Generated by Django 6.0.1 on 2026-04-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_delete_category_alter_filteroption_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtergroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='filters/groups/'),
        ),
        migrations.AddField(
            model_name='filteroption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='filters/options/'),
        ),
    ]
