# Generated by Django 6.0.1 on 2026-05-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_filtergroup_image_filteroption_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalog_country',
            field=models.CharField(blank=True, help_text='Specific country for the catalog', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_in_catalog',
            field=models.BooleanField(default=False),
        ),
    ]
