# Generated by Django 6.0.1 on 2026-05-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_product_sku_alter_productvariant_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catalog_country',
        ),
        migrations.AddField(
            model_name='product',
            name='catalog_countries',
            field=models.JSONField(blank=True, default=list, help_text="Specific countries for the catalog (e.g. ['USA', 'Canada']) or ['All']"),
        ),
    ]
