# Generated by Django 6.0.1 on 2026-02-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_contentsection_herosection_navbarpromo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsection',
            name='section_type',
            field=models.CharField(choices=[('banner', 'Banner Section'), ('featured', 'Featured Collection (Dynamic)'), ('catalogs', 'Shop by Catalog')], default='banner', max_length=20),
        ),
    ]
