# Generated by Django 6.0.1 on 2026-02-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_is_featured'),
        ('reviews', '0003_alter_contentsection_section_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentsection',
            options={},
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='section_type',
            field=models.CharField(choices=[('banner', 'Banner Section'), ('featured', 'Featured Collection (Dynamic)')], default='banner', max_length=20),
        ),
        migrations.CreateModel(
            name='ShopByCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Shop by Catalog', max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(related_name='shop_by_catalog', to='catalog.category')),
            ],
        ),
    ]
