# Generated by Django 6.0.1 on 2026-02-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_contentsection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentsection',
            options={'ordering': ['order']},
        ),
        migrations.DeleteModel(
            name='ShopByCatalog',
        ),
    ]
