# Generated by Django 6.0.1 on 2026-02-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_category_is_featured'),
        ('reviews', '0005_alter_contentsection_options_delete_shopbycatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopByCatalogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Shop by Collection', max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(blank=True, related_name='shop_by_catalog_sections', to='catalog.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
