# Generated by Django 6.0.1 on 2026-04-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_filtergroup_remove_category_parent_and_more'),
        ('reviews', '0006_shopbycatalogsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopbycatalogsection',
            name='categories',
        ),
        migrations.AddField(
            model_name='shopbycatalogsection',
            name='filters',
            field=models.ManyToManyField(blank=True, related_name='shop_by_catalog_sections', to='catalog.filteroption'),
        ),
    ]
