# Generated by Django 6.0.1 on 2026-04-02 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_filtergroup_image_filteroption_image'),
        ('reviews', '0007_remove_shopbycatalogsection_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsection',
            name='featured_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_sections', to='catalog.filteroption'),
        ),
    ]
