# Generated by Django 6.0.1 on 2026-04-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_contentsection_featured_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='button_link_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_text_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='content_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center')], default='center', max_length=10),
        ),
    ]
